version: '3.1'

services:
  db:
    image: mysql
    # env_file: _docker/.env
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dumps:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      retries: 5
